version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "lambda-openapi3-test"
resolve_s3 = true
s3_prefix = "lambda-openapi3-test"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = ""
